export const LINKS = {
  github: "https://github.com/senlindesign/coding-wrapped",
  practiceLibrary:
    "https://github.com/senlindesign/coding-wrapped/blob/accf079/skills/coding-wrapped/references/coding-best-practices.md",
  profile: "https://www.linkedin.com/in/senlinbebop",
  support: "https://buymeacoffee.com/senlin",
};

export const INSTALL_COMMAND = `npx skills add senlindesign/coding-wrapped \\
  --skill coding-wrapped \\
  --agent claude-code \\
  --agent codex \\
  --global`;

export const INSIGHTS = [
  {
    title: "The tiny-prompt commander",
    stat: "49% of your messages stayed under 50 characters.",
    summary: "Short prompts became a steering system: you set direction, inspect the result, then correct the next move.",
    youDid: "You pointed in a direction, then waited to see how the agent expanded it.",
    agentDid: "Short inputs often started a full implementation loop.",
    yourStyle: "You control rhythm and direction while leaving the expansion space to AI.",
    tip: "Add one finish line before a short command to save a confirmation loop.",
    practiceId: "define-outcome-boundaries",
    sourceIds: ["openai-prompting"],
    image: "/assets/illustrations/agent-orchestra-warm.webp",
    alt: "A pixel-art person directing a group of cream robots",
    theme: "warm",
  },
  {
    title: "The night-shift navigator",
    stat: "Your longest session ran for 160 focused minutes.",
    summary: "A single thread held enough context for decisions to compound instead of resetting with every task switch.",
    youDid: "Once momentum arrived, you stayed with one thread instead of switching projects.",
    agentDid: "The agent kept context and accumulated decisions across a long run.",
    yourStyle: "You work in deep expeditions rather than evenly spaced check-ins.",
    tip: "Leave a one-line checkpoint before the final late-night push.",
    practiceId: "evidence-before-done",
    sourceIds: ["anthropic-claude-code-best-practices"],
    image: "/assets/illustrations/night-runner-blue.webp",
    alt: "A pixel-art night runner scene with a car and coding agent",
    theme: "blue",
  },
  {
    title: "The prompt machine operator",
    stat: "One short sentence routinely became a multi-step build.",
    summary: "You hand over a compact instruction and let the agent assemble the missing production steps around it.",
    youDid: "You used compact requests to keep decisions moving quickly.",
    agentDid: "The agent inferred missing steps and assembled a production line around them.",
    yourStyle: "You prefer steering the system to documenting the entire route first.",
    tip: "Name the one thing that must not change when the task is sensitive.",
    practiceId: "define-outcome-boundaries",
    sourceIds: ["openai-prompting"],
    image: "/assets/illustrations/prompt-machine-pink.webp",
    alt: "A pixel-art workshop where a person hands prompts to several robots",
    theme: "pink",
  },
  {
    title: "The continue-button native",
    stat: "You said “continue” 10 times across active builds.",
    summary: "Once the direction is calibrated, continuity becomes your fastest way to protect momentum.",
    youDid: "When the direction felt right, you protected momentum with a single word.",
    agentDid: "The agent treated continuity as permission to preserve the working plan.",
    yourStyle: "You calibrate early, then let a trusted loop keep running.",
    tip: "Pair “continue” with one status line: done, blocked, and next.",
    practiceId: "explicit-agent-state",
    sourceIds: [
      "lenny-autonomous-coding-agents",
      "anthropic-claude-code-subagents",
    ],
    image: "/assets/illustrations/continue-steps-green.webp",
    alt: "A pixel-art library of coding robots and continuing work",
    theme: "green",
  },
];

export const METRICS = [
  { label: "Active days", value: "18", note: "of the last 30", kind: "activity" },
  { label: "Sessions", value: "23", note: "across 13 projects" },
  { label: "Longest run", value: "160m", note: "one continuous thread" },
  { label: "Messages", value: "111", note: "safe aggregate only" },
  { label: "Top model", value: "GPT-5", note: "52% of turns" },
  { label: "Tool calls", value: "286", note: "terminal led the mix" },
  { label: "Projects", value: "13", note: "active in this period" },
  { label: "Short prompts", value: "49%", note: "under 50 characters" },
];

const ZH_INSIGHTS = [
  {
    title: "短句指挥官",
    stat: "你发出的消息里，49% 不到 50 个字。",
    summary: "你习惯先给一个短方向，看结果，再补下一步。短提示就是你的方向盘。",
    youDid: "你先给方向，再根据结果继续往下带。",
    agentDid: "一句短指令，常常就会展开成一整套实现。",
    yourStyle: "你把握方向和节奏，具体怎么展开交给 AI。",
    tip: "发短指令时，多补一句“做到什么算完成”，通常能少来回一次。",
    practiceId: "define-outcome-boundaries",
    sourceIds: ["openai-prompting"],
    image: "/assets/illustrations/agent-orchestra-warm.webp",
    alt: "一位人物指挥一群奶油色机器人演奏的像素插画",
    theme: "warm",
  },
  {
    title: "夜间长跑者",
    stat: "你最长的一次连续会话，持续了 160 分钟。",
    summary: "你会把一件事留在同一段对话里做到底，让前面的判断一路接得上，不必反复重新说明。",
    youDid: "一进入状态，你更愿意沿着同一段对话继续做，而不是频繁换项目。",
    agentDid: "AI 沿用已有上下文，把前面做过的决定接着往下做。",
    yourStyle: "你习惯一口气深入，把问题做透。",
    tip: "长时间工作结束前，留一句“做到哪、还差什么”，下次接手会更顺。",
    practiceId: "evidence-before-done",
    sourceIds: ["anthropic-claude-code-best-practices"],
    image: "/assets/illustrations/night-runner-blue.webp",
    alt: "带有汽车和编程机器人的夜间像素长跑场景",
    theme: "blue",
  },
  {
    title: "一句话开工",
    stat: "一句短指令，常常就能带出好几个实现步骤。",
    summary: "你先说清要做什么，剩下的步骤让 AI 自己补齐。",
    youDid: "你用简短的要求快速推进，不在开头写满所有细节。",
    agentDid: "AI 补上中间步骤，把一句话变成可以落地的实现。",
    yourStyle: "你更愿意掌舵，不会事先规定每一步怎么走。",
    tip: "遇到不能出错的任务，记得补一句“这部分不要改”。",
    practiceId: "define-outcome-boundaries",
    sourceIds: ["openai-prompting"],
    image: "/assets/illustrations/prompt-machine-pink.webp",
    alt: "人物把提示交给多位机器人的像素工坊",
    theme: "pink",
  },
  {
    title: "“继续”按钮本人",
    stat: "你在进行中的任务里，说了 10 次“继续”。",
    summary: "方向对了以后，你更愿意顺着当前思路接着做，不轻易打断节奏。",
    youDid: "确认方向没问题后，你用一句“继续”让工作接着往下走。",
    agentDid: "AI 沿用当前计划和上下文，继续完成剩下的工作。",
    yourStyle: "前面多校准，后面少打断。",
    tip: "继续前，让 AI 用一行说明：已完成、卡点、下一步。",
    practiceId: "explicit-agent-state",
    sourceIds: ["lenny-autonomous-coding-agents", "anthropic-claude-code-subagents"],
    image: "/assets/illustrations/continue-steps-green.webp",
    alt: "充满编程机器人和持续工作的绿色像素图书馆",
    theme: "green",
  },
];

const ZH_METRICS = [
  { label: "活跃天数", value: "18", note: "过去 30 天", kind: "activity" },
  { label: "会话次数", value: "23", note: "涉及 13 个项目" },
  { label: "最长连续工作", value: "160m", note: "在同一段对话里" },
  { label: "你的消息", value: "111", note: "只统计汇总数据" },
  { label: "常用模型", value: "GPT-5", note: "占全部回合的 52%" },
  { label: "工具调用", value: "286", note: "最常使用终端" },
  { label: "项目数", value: "13", note: "本期有记录" },
  { label: "短提示", value: "49%", note: "不到 50 个字" },
];

const EN_UI = {
  lang: "中文",
  languageLabel: "Language",
  agentSupported: "supported",
  hero: {
    mascotAlt: "Coding Wrapped — a pixel robot reading its coding log",
    slogan: "Observe the way you build",
    body: "Turn local AI-coding history into revealing stories and practical next steps. One shot. Nothing leaves your machine.",
    install: "Install Skill",
    github: "Go to GitHub",
    nowWorks: "Now works with",
    supportedAgents: "Supported coding agents",
  },
  dock: ["Coding Wrapped", "GitHub", "About Sen", "Support the project"],
  overview: {
    kicker: "Your coding overview",
    title: "You steer by correction, not by specification.",
    body: "Across 23 sessions, your short prompts kept work moving while the agent carried the implementation detail. Your clearest pattern is a fast loop: point, inspect, adjust, continue.",
    patterns: [
      { title: "Short prompts", copy: "Point, inspect, then adjust instead of writing the whole route upfront." },
      { title: "Long runs", copy: "Stay inside one thread long enough for decisions to compound." },
      { title: "Calibration", copy: "Use small corrections to keep a trusted agent loop moving." },
    ],
    patternsLabel: "Three coding patterns",
    sources: "Sources",
    sessions: ["18 sessions", "5 sessions"],
    privacy: "Local aggregates only · no transcript leaves your machine",
  },
  insight: {
    current: "Current insight",
    label: "Insight stories. Use left and right arrow keys or swipe to change the story.",
    built: "Built from local demo data · auto play",
    choose: "Choose an insight",
    show: "Show insight",
    previous: "Prev",
    next: "Next",
    swipe: "Swipe or use arrow keys",
    imageLabel: "An illustrated insight card stack. Drag or swipe horizontally to change insight.",
    did: ["You did", "Agent did", "Your style"],
    tip: "Light tip",
  },
  data: {
    activity: "30 day activity grid",
    kicker: "Your coding behavior",
    title: "Choose the facts that explain the pattern.",
    body: "All blocks are safe aggregates. Select up to eight for the view you want to keep.",
    customize: "Customize",
    visible: "Choose visible metrics",
    on: "On",
    off: "Off",
    source: "Factual layer · derived locally from session aggregates",
  },
  demo: {
    title: "Live demo · 127.0.0.1 / coding-wrapped",
    brand: "Coding Wrapped",
    locality: "Personal / local",
    adventure: "Sen's coding adventure log",
    subtitle: "See how you and AI actually get things made together.",
    ownData: "Use my own data",
    views: ["Coding overview", "Insight deck", "Behavior data"],
    viewLabel: "Demo views",
    status: "Live preview · local-first",
  },
  process: {
    kicker: "Three small steps",
    title: "From local traces to a story you recognize.",
    alt: "A pixel-art flow from scanning local coding logs, to wrapping safe data, to exploring finished insights",
    rows: [["Scan", "Read standard Claude Code and Codex session folders locally."], ["Wrap", "Turn safe aggregates into an overview and four distinct insights."], ["Explore", "Open a private localhost dashboard, refresh facts, or export intentionally."]],
    privacy: "Raw conversations, source code, project names, local paths and secrets stay out of the website.",
  },
  tips: {
    kicker: "Useful tips",
    title: "Small tips for your next coding session.",
    body: "Coding Wrapped matches patterns in your local aggregates with trusted practices, then suggests one lightweight next move for your next coding session.",
    library: "View the practice library",
    sourceTypesLabel: "Practice source types",
    sourceTypes: ["Official guidance", "Practitioner playbooks", "Expert conversations"],
    lightTip: "Light tip",
    matched: "Matched to · short prompts",
    example: "Add one sentence describing what done looks like and one thing that must not change.",
    basedOn: "Based on",
    source: "OpenAI · Prompting",
    alt: "A pixel-art robot offering one lightweight tip before the coder's next session",
  },
  install: {
    kicker: "One command · Claude Code + Codex",
    title: "Give your coding history a plot.",
    body: "Install the same open Agent Skill on both platforms. No separate product and no cloud account.",
    copy: "Copy command",
    docs: "Read the docs",
  },
  footer: { license: "MIT · open source" },
  toast: { copied: "Install command copied.", fallback: "Select the command in the install window to copy it." },
};

const ZH_UI = {
  lang: "EN",
  languageLabel: "语言",
  agentSupported: "已支持",
  hero: {
    mascotAlt: "Coding Wrapped：一个正在阅读编程日志的像素机器人",
    slogan: "看见你和 AI 是怎么一起做事的",
    body: "把本地的 AI 编程记录，变成关于你如何工作的有趣故事，再给你几条下次就能试的小建议。运行一次即可，所有数据都留在你的电脑上。",
    install: "安装 Skill",
    github: "前往 GitHub",
    nowWorks: "现已支持",
    supportedAgents: "支持的编程 Agent",
  },
  dock: ["Coding Wrapped", "GitHub", "关于 Sen", "支持这个项目"],
  overview: {
    kicker: "你的编程总览",
    title: "你习惯边做边调，靠一次次校准把事情做成。",
    body: "过去 23 次对话里，你常用短提示推动工作，具体实现更多交给 AI。最常见的节奏是：给方向、看结果、再调整、继续做。",
    patterns: [
      { title: "短提示", copy: "先给方向，看结果，再补下一步，不会一上来就把整条路线写死。" },
      { title: "长时间专注", copy: "沿着同一段对话做得很深，让前面的决定接着发挥作用。" },
      { title: "随时校准", copy: "发现偏了就小幅修正，让 AI 沿着靠谱的方向继续做。" },
    ],
    patternsLabel: "三种常见习惯",
    sources: "来源",
    sessions: ["18 次会话", "5 次会话"],
    privacy: "这里只用本地汇总数据 · 原始对话不会离开你的电脑",
  },
  insight: {
    current: "本期洞察",
    label: "用左右方向键，或直接滑动，切换不同故事。",
    built: "本地演示数据 · 自动播放",
    choose: "选择一条洞察",
    show: "查看第",
    previous: "上一张",
    next: "下一张",
    swipe: "滑动或使用方向键",
    imageLabel: "一组带插画的洞察卡，可以横向拖动或滑动切换。",
    did: ["你怎么做", "AI 怎么做", "你的风格"],
    tip: "小建议",
  },
  data: {
    activity: "30 天活跃点阵图",
    kicker: "你的编程习惯",
    title: "选出最能说明你工作方式的数据。",
    body: "这里展示的都是本地汇总数据。最多选八项，留下你最想看的内容。",
    customize: "自定义",
    visible: "选择展示的数据",
    on: "开启",
    off: "关闭",
    source: "数据来自本地会话汇总",
  },
  demo: {
    title: "实时演示 · 127.0.0.1 / coding-wrapped",
    brand: "Coding Wrapped",
    locality: "个人数据 / 仅本地",
    adventure: "Sen 的编程冒险日志",
    subtitle: "看看你和 AI 平时是怎么一起把事情做出来的。",
    ownData: "换成我的数据",
    views: ["编程总览", "洞察卡组", "习惯数据"],
    viewLabel: "演示视图",
    status: "实时预览 · 数据留在本地",
  },
  process: {
    kicker: "三步完成",
    title: "从本地记录，变成一眼就懂的故事。",
    alt: "从读取本地编程记录、整理安全数据，到查看完整故事的像素流程图",
    rows: [["读取", "在你的电脑上读取 Claude Code 和 Codex 的标准会话目录。"], ["整理", "只提取安全的汇总数据，生成一份总览和四张洞察卡。"], ["查看", "在本地打开专属页面，刷新数据，需要时再导出。"]],
    privacy: "原始对话、源代码、项目名称、本地路径和密钥都不会进入这个网站。",
  },
  tips: {
    kicker: "下次可以试试",
    title: "给下一次编程，一点小提示。",
    body: "Coding Wrapped 会根据你的本地使用习惯，从可信的实践经验里挑一条最适合你下次尝试的小建议。",
    library: "查看实践库",
    sourceTypesLabel: "建议参考来源",
    sourceTypes: ["官方指南", "实践者经验", "专家分享"],
    lightTip: "小建议",
    matched: "对应习惯 · 短提示",
    example: "补一句“做完是什么样”，再说清一件绝不能改变的事。",
    basedOn: "参考",
    source: "OpenAI · 提示词指南",
    alt: "一个像素机器人在创作者开始下一次编程前递来一条小建议",
  },
  install: {
    kicker: "一条命令，同时支持 Claude Code 和 Codex",
    title: "让你的编程记录，有故事可讲。",
    body: "Claude Code 和 Codex 共用同一个开源 Skill，不用注册新产品，也不用把数据传到云端。",
    copy: "复制安装命令",
    docs: "查看文档",
  },
  footer: { license: "MIT · 开源" },
  toast: { copied: "已复制安装命令。", fallback: "请选中安装窗口里的命令再复制。" },
};

export function getLocalizedContent(locale) {
  return locale === "zh"
    ? { insights: ZH_INSIGHTS, metrics: ZH_METRICS, ui: ZH_UI }
    : { insights: INSIGHTS, metrics: METRICS, ui: EN_UI };
}
