export const LINKS = {
  github: "https://github.com/senlindesign/coding-wrapped",
  practiceLibrary:
    "https://github.com/senlindesign/coding-wrapped/blob/accf079/skills/coding-wrapped/references/coding-best-practices.md",
  profile: "https://www.linkedin.com/in/senlinbebop",
  support: "https://buymeacoffee.com/senlin",
};

export const INSTALL_COMMAND = `npx skills add senlindesign/coding-wrapped \\
  --skill coding-wrapped \\
  --agent claude-code \\
  --agent codex \\
  --global`;

export const INSIGHTS = [
  {
    title: "The tiny-prompt commander",
    stat: "49% of your messages stayed under 50 characters.",
    summary: "Short prompts became a steering system: you set direction, inspect the result, then correct the next move.",
    youDid: "You pointed in a direction, then waited to see how the agent expanded it.",
    agentDid: "Short inputs often started a full implementation loop.",
    yourStyle: "You control rhythm and direction while leaving the expansion space to AI.",
    tip: "Add one finish line before a short command to save a confirmation loop.",
    practiceId: "define-outcome-boundaries",
    sourceIds: ["openai-prompting"],
    image: "/assets/illustrations/agent-orchestra-warm.webp",
    alt: "A pixel-art person directing a group of cream robots",
    theme: "warm",
  },
  {
    title: "The night-shift navigator",
    stat: "Your longest session ran for 160 focused minutes.",
    summary: "A single thread held enough context for decisions to compound instead of resetting with every task switch.",
    youDid: "Once momentum arrived, you stayed with one thread instead of switching projects.",
    agentDid: "The agent kept context and accumulated decisions across a long run.",
    yourStyle: "You work in deep expeditions rather than evenly spaced check-ins.",
    tip: "Leave a one-line checkpoint before the final late-night push.",
    practiceId: "evidence-before-done",
    sourceIds: ["anthropic-claude-code-best-practices"],
    image: "/assets/illustrations/night-runner-blue.webp",
    alt: "A pixel-art night runner scene with a car and coding agent",
    theme: "blue",
  },
  {
    title: "The prompt machine operator",
    stat: "One short sentence routinely became a multi-step build.",
    summary: "You hand over a compact instruction and let the agent assemble the missing production steps around it.",
    youDid: "You used compact requests to keep decisions moving quickly.",
    agentDid: "The agent inferred missing steps and assembled a production line around them.",
    yourStyle: "You prefer steering the system to documenting the entire route first.",
    tip: "Name the one thing that must not change when the task is sensitive.",
    practiceId: "define-outcome-boundaries",
    sourceIds: ["openai-prompting"],
    image: "/assets/illustrations/prompt-machine-pink.webp",
    alt: "A pixel-art workshop where a person hands prompts to several robots",
    theme: "pink",
  },
  {
    title: "The continue-button native",
    stat: "You said “continue” 10 times across active builds.",
    summary: "Once the direction is calibrated, continuity becomes your fastest way to protect momentum.",
    youDid: "When the direction felt right, you protected momentum with a single word.",
    agentDid: "The agent treated continuity as permission to preserve the working plan.",
    yourStyle: "You calibrate early, then let a trusted loop keep running.",
    tip: "Pair “continue” with one status line: done, blocked, and next.",
    practiceId: "explicit-agent-state",
    sourceIds: [
      "lenny-autonomous-coding-agents",
      "anthropic-claude-code-subagents",
    ],
    image: "/assets/illustrations/continue-steps-green.webp",
    alt: "A pixel-art library of coding robots and continuing work",
    theme: "green",
  },
];

export const METRICS = [
  { label: "Active days", value: "18", note: "of the last 30", kind: "activity" },
  { label: "Sessions", value: "23", note: "across 13 projects" },
  { label: "Longest run", value: "160m", note: "one continuous thread" },
  { label: "Messages", value: "111", note: "safe aggregate only" },
  { label: "Top model", value: "GPT-5", note: "52% of turns" },
  { label: "Tool calls", value: "286", note: "terminal led the mix" },
  { label: "Projects", value: "13", note: "active in this period" },
  { label: "Short prompts", value: "49%", note: "under 50 characters" },
];

const ZH_INSIGHTS = [
  {
    title: "短句指挥官",
    stat: "49% 的消息不超过 50 个字。",
    summary: "短提示成了你的操控系统：定一个方向，看一眼结果，再校准下一步。",
    youDid: "你先指出一个方向，再看 AI 如何把它展开。",
    agentDid: "很短的输入，往往启动了一整套实现循环。",
    yourStyle: "你掌控节奏和方向，把展开空间留给 AI。",
    tip: "短指令前补一句完成标准，通常能少一次来回确认。",
    practiceId: "define-outcome-boundaries",
    sourceIds: ["openai-prompting"],
    image: "/assets/illustrations/agent-orchestra-warm.webp",
    alt: "一位人物指挥一群奶油色机器人演奏的像素插画",
    theme: "warm",
  },
  {
    title: "夜间长跑者",
    stat: "你最长的一次专注会话持续了 160 分钟。",
    summary: "同一个线程容纳了足够的上下文，让判断可以累积，而不是每次切换任务都重来。",
    youDid: "一旦进入状态，你会留在同一个线程，而不是频繁切换项目。",
    agentDid: "AI 在一次长跑中保留上下文，并逐步累积已做出的判断。",
    yourStyle: "你更像是在进行深度远征，而不是均匀分布的小检查。",
    tip: "在深夜最后一段冲刺前，留下一句当前状态的检查点。",
    practiceId: "evidence-before-done",
    sourceIds: ["anthropic-claude-code-best-practices"],
    image: "/assets/illustrations/night-runner-blue.webp",
    alt: "带有汽车和编程机器人的夜间像素长跑场景",
    theme: "blue",
  },
  {
    title: "提示词机器操作员",
    stat: "一句短指令，经常会变成一次多步骤构建。",
    summary: "你交出一个紧凑的指令，让 AI 把其余的生产步骤组装出来。",
    youDid: "你用紧凑的请求，让决策持续向前。",
    agentDid: "AI 推断遗漏的步骤，并在周围搭起一条生产线。",
    yourStyle: "你喜欢操控系统，不先把整条路线写完。",
    tip: "任务敏感时，明确说出那一件绝不能改变的事。",
    practiceId: "define-outcome-boundaries",
    sourceIds: ["openai-prompting"],
    image: "/assets/illustrations/prompt-machine-pink.webp",
    alt: "人物把提示交给多位机器人的像素工坊",
    theme: "pink",
  },
  {
    title: "继续按钮本人",
    stat: "你在活跃构建中说了 10 次“继续”。",
    summary: "方向校准之后，连续性成了你保护工作势头最快的方式。",
    youDid: "当方向正确时，你用一个词守住了势头。",
    agentDid: "AI 将“继续”理解为沿用当前计划的许可。",
    yourStyle: "你先早早校准，再让一个可信的循环持续运行。",
    tip: "“继续”前加一行状态：已完成、卡点和下一步。",
    practiceId: "explicit-agent-state",
    sourceIds: ["lenny-autonomous-coding-agents", "anthropic-claude-code-subagents"],
    image: "/assets/illustrations/continue-steps-green.webp",
    alt: "充满编程机器人和持续工作的绿色像素图书馆",
    theme: "green",
  },
];

const ZH_METRICS = [
  { label: "活跃天数", value: "18", note: "过去 30 天", kind: "activity" },
  { label: "会话", value: "23", note: "横跨 13 个项目" },
  { label: "最长长跑", value: "160m", note: "同一连续线程" },
  { label: "消息", value: "111", note: "仅安全聚合数据" },
  { label: "常用模型", value: "GPT-5", note: "占 52% 回合" },
  { label: "工具调用", value: "286", note: "终端占比最高" },
  { label: "项目", value: "13", note: "本期活跃" },
  { label: "短提示", value: "49%", note: "少于 50 个字符" },
];

const EN_UI = {
  lang: "中文",
  languageLabel: "Language",
  agentSupported: "supported",
  hero: {
    mascotAlt: "Coding Wrapped — a pixel robot reading its coding log",
    slogan: "Observe the way you build",
    body: "Turn local AI-coding history into revealing stories and practical next steps. One shot. Nothing leaves your machine.",
    install: "Install Skill",
    github: "Go to GitHub",
    nowWorks: "Now works with",
    supportedAgents: "Supported coding agents",
  },
  dock: ["Coding Wrapped", "GitHub", "About Sen", "Support the project"],
  overview: {
    kicker: "Your coding overview",
    title: "You steer by correction, not by specification.",
    body: "Across 23 sessions, your short prompts kept work moving while the agent carried the implementation detail. Your clearest pattern is a fast loop: point, inspect, adjust, continue.",
    patterns: [
      { title: "Short prompts", copy: "Point, inspect, then adjust instead of writing the whole route upfront." },
      { title: "Long runs", copy: "Stay inside one thread long enough for decisions to compound." },
      { title: "Calibration", copy: "Use small corrections to keep a trusted agent loop moving." },
    ],
    patternsLabel: "Three coding patterns",
    sources: "Sources",
    sessions: ["18 sessions", "5 sessions"],
    privacy: "Local aggregates only · no transcript leaves your machine",
  },
  insight: {
    current: "Current insight",
    label: "Insight stories. Use left and right arrow keys or swipe to change the story.",
    built: "Built from local demo data · auto play",
    choose: "Choose an insight",
    show: "Show insight",
    previous: "Prev",
    next: "Next",
    swipe: "Swipe or use arrow keys",
    imageLabel: "An illustrated insight card stack. Drag or swipe horizontally to change insight.",
    did: ["You did", "Agent did", "Your style"],
    tip: "Light tip",
  },
  data: {
    activity: "30 day activity grid",
    kicker: "Your coding behavior",
    title: "Choose the facts that explain the pattern.",
    body: "All blocks are safe aggregates. Select up to eight for the view you want to keep.",
    customize: "Customize",
    visible: "Choose visible metrics",
    on: "On",
    off: "Off",
    source: "Factual layer · derived locally from session aggregates",
  },
  demo: {
    title: "Live demo · 127.0.0.1 / coding-wrapped",
    brand: "Coding Wrapped",
    locality: "Personal / local",
    adventure: "Sen's coding adventure log",
    subtitle: "See how you and AI actually get things made together.",
    ownData: "Use my own data",
    views: ["Coding overview", "Insight deck", "Behavior data"],
    viewLabel: "Demo views",
    status: "Live preview · local-first",
  },
  process: {
    kicker: "Three small steps",
    title: "From local traces to a story you recognize.",
    alt: "A pixel-art flow from scanning local coding logs, to wrapping safe data, to exploring finished insights",
    rows: [["Scan", "Read standard Claude Code and Codex session folders locally."], ["Wrap", "Turn safe aggregates into an overview and four distinct insights."], ["Explore", "Open a private localhost dashboard, refresh facts, or export intentionally."]],
    privacy: "Raw conversations, source code, project names, local paths and secrets stay out of the website.",
  },
  tips: {
    kicker: "Useful tips",
    title: "Small tips for your next coding session.",
    body: "Coding Wrapped matches patterns in your local aggregates with trusted practices, then suggests one lightweight next move for your next coding session.",
    library: "View the practice library",
    sourceTypes: ["Official guidance", "Practitioner playbooks", "Expert conversations"],
    lightTip: "Light tip",
    matched: "Matched to · short prompts",
    example: "Add one sentence describing what done looks like and one thing that must not change.",
    basedOn: "Based on",
    source: "OpenAI · Prompting",
    alt: "A pixel-art robot offering one lightweight tip before the coder's next session",
  },
  install: {
    kicker: "One command · Claude Code + Codex",
    title: "Give your coding history a plot.",
    body: "Install the same open Agent Skill on both platforms. No separate product and no cloud account.",
    copy: "Copy command",
    docs: "Read the docs",
  },
  footer: { license: "MIT · open source" },
  toast: { copied: "Install command copied.", fallback: "Select the command in the install window to copy it." },
};

const ZH_UI = {
  lang: "EN",
  languageLabel: "语言",
  agentSupported: "已支持",
  hero: {
    mascotAlt: "Coding Wrapped：一个正在阅读编程日志的像素机器人",
    slogan: "看见你与 AI 共创的轨迹",
    body: "把本地 AI 编程记录变成有意思的故事和下一步建议。一次运行，数据不离开你的电脑。",
    install: "安装 Skill",
    github: "前往 GitHub",
    nowWorks: "现已支持",
    supportedAgents: "支持的编程智能体",
  },
  dock: ["Coding Wrapped", "GitHub", "关于 Sen", "支持这个项目"],
  overview: {
    kicker: "你的编程总览",
    title: "你靠校准前进，而不是靠写满规格。",
    body: "在 23 次会话里，短提示让工作持续向前，AI 承担了实现细节。你最清晰的模式是一条快速循环：指出、检查、调整、继续。",
    patterns: [
      { title: "短提示", copy: "先指出方向、检查结果，再调整，而不是一开始就写完整路线。" },
      { title: "长跑", copy: "在同一个线程里停留得足够久，让判断自然累积。" },
      { title: "校准", copy: "用小幅修正，让可信的智能体循环持续向前。" },
    ],
    patternsLabel: "三种编程模式",
    sources: "来源",
    sessions: ["18 次会话", "5 次会话"],
    privacy: "仅本地聚合数据 · 原始对话不会离开你的设备",
  },
  insight: {
    current: "本期洞察",
    label: "洞察故事。使用左右方向键或滑动切换故事。",
    built: "基于本地演示数据 · 自动播放",
    choose: "选择一张洞察卡",
    show: "显示第",
    previous: "上一张",
    next: "下一张",
    swipe: "滑动或使用方向键",
    imageLabel: "一组插画洞察卡。横向拖动或滑动切换。",
    did: ["你怎么做", "AI 怎么做", "你的风格"],
    tip: "轻建议",
  },
  data: {
    activity: "30 天活跃点阵图",
    kicker: "你的编程行为",
    title: "挑选能解释这段模式的事实。",
    body: "所有区块都只展示安全聚合数据。最多选八项，保留你想看的视图。",
    customize: "自定义",
    visible: "选择展示的数据",
    on: "开启",
    off: "关闭",
    source: "事实层 · 由本地会话聚合数据得出",
  },
  demo: {
    title: "实时演示 · 127.0.0.1 / coding-wrapped",
    brand: "Coding Wrapped",
    locality: "个人 / 本地",
    adventure: "Sen 的编程冒险日志",
    subtitle: "看看你和 AI 是怎样一起把事情做出来的。",
    ownData: "使用我的数据",
    views: ["编程总览", "洞察卡组", "行为数据"],
    viewLabel: "演示视图",
    status: "实时预览 · 本地优先",
  },
  process: {
    kicker: "三个小步骤",
    title: "从本地痕迹，到你认得出的故事。",
    alt: "从扫描本地编程记录、整理安全数据，到探索完成洞察的像素流程图",
    rows: [["扫描", "在本地读取 Claude Code 和 Codex 的标准会话目录。"], ["整理", "把安全聚合数据做成一个总览和四张不同的洞察卡。"], ["探索", "打开私有 localhost 仪表盘，刷新事实，或按需导出。"]],
    privacy: "原始对话、源代码、项目名称、本地路径和密钥都不会进入这个网站。",
  },
  tips: {
    kicker: "实用小建议",
    title: "为下一次编程准备的小提示。",
    body: "Coding Wrapped 会将你的本地聚合模式与可信实践相匹配，为下一次编程给出一条轻量建议。",
    library: "查看实践库",
    sourceTypes: ["官方指南", "实践者方法", "专家对谈"],
    lightTip: "轻建议",
    matched: "匹配到 · 短提示",
    example: "补一句“做完是什么样”，再说清一件绝不能改变的事。",
    basedOn: "基于",
    source: "OpenAI · 提示工程",
    alt: "一个像素机器人在下一次编程前递给创作者一条轻量建议",
  },
  install: {
    kicker: "一条命令 · Claude Code + Codex",
    title: "给你的编程记录一个故事。",
    body: "在两个平台安装同一个开放的 Agent Skill。不需要单独产品，也不需要云端账号。",
    copy: "复制命令",
    docs: "阅读文档",
  },
  footer: { license: "MIT · 开源" },
  toast: { copied: "安装命令已复制。", fallback: "请在安装窗口中选中命令后复制。" },
};

export function getLocalizedContent(locale) {
  return locale === "zh"
    ? { insights: ZH_INSIGHTS, metrics: ZH_METRICS, ui: ZH_UI }
    : { insights: INSIGHTS, metrics: METRICS, ui: EN_UI };
}
